[package]
name = "neat-api"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
